#!/bin/bash
#
# lib/OS10-FE-Networking
# # Functions to control the configuration and operation of the **OS10 FE Networking**

# Dependencies:
# (none)

# Save trace setting
_XTRACE_OS10_FE_NETWORKING=$(set +o | grep xtrace)
set +o xtrace

# Defaults
# --------

# os10-fe-networking service
OS10_FE_NETWORKING_REPO=${OS10_FE_NETWORKING_REPO:-${GIT_BASE}/Dell-EMC-Cloud/OS10-FE-Networking.git}
OS10_FE_NETWORKING_BRANCH=${OS10_FE_NETWORKING_BRANCH:-main}

OS10_FE_NETWORKING_DIR=${OS10_FE_NETWORKING_DIR:-$DEST/OS10-FE-Networking}
OS10_FE_NETWORKING_BRANCH_DATA_DIR=""$DATA_DIR/OS10-FE-Networking""

# Support entry points installation of console scripts
OS10_FE_NETWORKING_BIN_DIR=$(get_python_exec_prefix)

OS10_FE_CONF_DIR=${OS10_FE_CONF_DIR:-/etc/neutron/plugins/os10_fe}
OS10_FE_CONF_FILE_LEAF1=$OS10_FE_CONF_DIR/leaf1.ini
OS10_FE_CONF_FILE_LEAF2=$OS10_FE_CONF_DIR/leaf2.ini
OS10_FE_CONF_FILE_SPINE1=$OS10_FE_CONF_DIR/spine1.ini
OS10_FE_CONF_FILE_SPINE2=$OS10_FE_CONF_DIR/spine2.ini


# Functions
# ---------

function install_os10_fe_networking {
    setup_develop $OS10_FE_NETWORKING_DIR
}


function configure_os10_fe_networking {
	sudo install -d -o $STACK_USER $OS10_FE_CONF_DIR

	(cd $OS10_FE_NETWORKING_DIR && exec oslo-config-generator --config-file ./tools/config/os10-fe-networking-config-generator.conf)

	cp $OS10_FE_NETWORKING_DIR/os10_fe.conf.sample $OS10_FE_CONF_FILE_LEAF1
	cp $OS10_FE_NETWORKING_DIR/os10_fe.conf.sample $OS10_FE_CONF_FILE_LEAF2
	cp $OS10_FE_NETWORKING_DIR/os10_fe.conf.sample $OS10_FE_CONF_FILE_SPINE1
	cp $OS10_FE_NETWORKING_DIR/os10_fe.conf.sample $OS10_FE_CONF_FILE_SPINE2

	NEUTRON_CORE_PLUGIN='os10_ml2'
    iniset $NEUTRON_CONF DEFAULT core_plugin $NEUTRON_CORE_PLUGIN
}

function configure_os10_fe_networking_neutron_agent {
    configure_keystone_authtoken_middleware $NEUTRON_CONF ironic ironic
    configure_placement_nova_compute $NEUTRON_CONF
}

function start_os10_fe_networking_neutron_agent {
    run_process os10-neutronagt-leaf1 "$OS10_FE_NETWORKING_BIN_DIR/os10-fe-neutron-agent --config-file $NEUTRON_CONF --config-file $NEUTRON_CORE_PLUGIN_CONF --config-file $OS10_FE_CONF_FILE_LEAF1"
    run_process os10-neutronagt-leaf2 "$OS10_FE_NETWORKING_BIN_DIR/os10-fe-neutron-agent --config-file $NEUTRON_CONF --config-file $NEUTRON_CORE_PLUGIN_CONF --config-file $OS10_FE_CONF_FILE_LEAF2"
    run_process os10-neutronagt-spine1 "$OS10_FE_NETWORKING_BIN_DIR/os10-fe-neutron-agent --config-file $NEUTRON_CONF --config-file $NEUTRON_CORE_PLUGIN_CONF --config-file $OS10_FE_CONF_FILE_SPINE1"
    run_process os10-neutronagt-spine2 "$OS10_FE_NETWORKING_BIN_DIR/os10-fe-neutron-agent --config-file $NEUTRON_CONF --config-file $NEUTRON_CORE_PLUGIN_CONF --config-file $OS10_FE_CONF_FILE_SPINE2"
}

function stop_os10_fe_networking_neutron_agent {
    stop_process os10-neutronagt-leaf1
    stop_process os10-neutronagt-leaf2
    stop_process os10-neutronagt-spine1
    stop_process os10-neutronagt-spine2
}

function cleanup_os10_fe_networking {
    rm -rf $OS10_FE_NETWORKING_BRANCH_DATA_DIR
}
